[DEFAULT]
ConnectionType=acceptor
ResetOnLogon=Y
LogonTimeout=6000
ReconnectInterval=6030
FileLogPath=/Users/sandeepknair/Documents/temp/QuickFixJ/acceptor/logs

[SESSION]
BeginString=FIX.4.2
SenderCompID=TRIO-ACCEPTOR-SERVICE
TargetCompID=TRIO-INITIATOR-SERVICE
StartDay=sunday
EndDay=friday
StartTime=00:00:00
EndTime=00:00:00
HeartBtInt=30
CheckLatency=N
SocketAcceptPort=12000
UseDataDictionary=Y
DataDictionary=FIX42.xml
FileStorePath=/Users/sandeepknair/Documents/temp/QuickFixJ/ICE